import type { Metadata } from 'next'
import { Section } from '@/components/section'
import { createPageMetadata } from '@/lib/metadata'

export const metadata: Metadata = createPageMetadata({
  title: 'SafeToken Project',
  description:
    'Interswitch authentication service for issuing, delivering, and validating OTPs across payment and identity-verification flows.',
  path: '/case-studies/safetoken-3ds'
})

export default function SafeTokenCaseStudyPage() {
  return (
    <div className="container page">
      <Section
        title="SafeToken Project"
        intro="An Interswitch authentication service for issuing, delivering, and validating one-time passwords used in payment and identity-verification flows."
      >
        <div className="stack">
          <div>
            <h3>Overview</h3>
            <p>
              SafeToken supports three authentication methods: service-issued
              OTPs delivered by SMS or email, authenticator-app TOTP
              credentials provisioned through QR codes, and counter-based OTPs
              generated by physical hard-token devices.
            </p>
          </div>

          <div>
            <h3>Core workflow</h3>
            <ul className="list">
              <li>A token requestor or aggregator calls the API using an API key</li>
              <li>SafeToken identifies the customer token and permitted authentication methods</li>
              <li>It generates, sends, or validates the OTP locally or through an external provider</li>
              <li>Successful authentication returns transaction status, ECI, and a CAVV-style authentication token</li>
              <li>Each attempt is logged for auditing, reporting, and billing</li>
            </ul>
          </div>

          <div>
            <h3>Main capabilities</h3>
            <ul className="list">
              <li>Token registration, activation, update, and retrieval</li>
              <li>OTP generation, validation, and authentication</li>
              <li>Authenticator-app provisioning through QR codes</li>
              <li>Requestor and aggregator authorization</li>
              <li>SMS and email OTP delivery</li>
              <li>Configurable external OTP providers including GTB, ZIB, Rolez, and generic third parties</li>
              <li>Multiple regional SMS providers plus delivery reports and callbacks</li>
              <li>Validation history, correlation IDs, Wibmo reporting, and legacy token compatibility</li>
            </ul>
          </div>

          <div>
            <h3>Architecture and technology</h3>
            <ul className="list">
              <li>Java 25 and Spring Boot 4 REST application</li>
              <li>Controllers for external APIs and services for token and authentication rules</li>
              <li>Provider abstractions for external OTP, SMS, and email systems</li>
              <li>JDBC DAOs backed by Microsoft SQL Server</li>
              <li>Redis for temporary OTP and request-session data</li>
              <li>Kafka for asynchronous validation reports</li>
              <li>Flyway and an internal migrator for database changes</li>
              <li>HSM integration for cryptographic authentication-token generation</li>
              <li>OpenAPI/Swagger, Actuator, structured logging, and Docker deployment</li>
            </ul>
          </div>

          <div>
            <h3>Why it matters</h3>
            <p>
              The platform sits in a security-sensitive part of the payments
              stack, so correctness, traceability, delivery reliability, and
              partner integration behavior all matter at the same time.
            </p>
          </div>
        </div>
      </Section>
    </div>
  )
}
