import type { Metadata } from 'next'
import { Section } from '@/components/section'
import { createPageMetadata } from '@/lib/metadata'

export const metadata: Metadata = createPageMetadata({
  title: 'SafeToken Project',
  description:
    'Interswitch authentication service for issuing, delivering, and validating OTPs across payment and identity-verification flows.',
  path: '/case-studies/safetoken-3ds'
})

export default function SafeTokenCaseStudyPage() {
  return (
    <div className="container page">
      <Section
        headingLevel="h1"
        title="SafeToken Project"
        intro="Customer-facing integration engineering for a payment-authentication platform used by banks, fintechs, card issuers, and payment gateways."
      >
        <div className="stack">
          <div>
            <h2>Overview</h2>
            <p>
              SafeToken supports three authentication methods: service-issued
              OTPs delivered by SMS or email, authenticator-app TOTP
              credentials provisioned through QR codes, and counter-based OTPs
              generated by physical hard-token devices.
            </p>
          </div>

          <div>
            <h2>Customer and transaction flow</h2>
            <ul className="list">
              <li>Banks, fintechs, and card issuers enrol card tokens individually or through bulk uploads</li>
              <li>A payment gateway initiates validation for a cardholder transaction</li>
              <li>SafeToken generates an OTP and delivers it through an internal or configured third-party provider</li>
              <li>The gateway submits the cardholder's OTP to SafeToken for authentication</li>
              <li>The authenticated transaction proceeds to the issuing bank for authorization</li>
            </ul>
          </div>

          <div>
            <h2>My role</h2>
            <p>
              As a technical integration engineer, I supported external partners
              integrating token enrolment, OTP validation, delivery, and
              authentication flows. I investigated technical issues across partner
              requests, SafeToken services, and configured providers, then engaged
              the required product, engineering, and operational stakeholders to
              implement fixes and reach a production resolution.
            </p>
          </div>

          <div>
            <h2>Main capabilities</h2>
            <ul className="list">
              <li>Token registration, activation, update, and retrieval</li>
              <li>OTP generation, validation, and authentication</li>
              <li>Authenticator-app provisioning through QR codes</li>
              <li>Requestor and aggregator authorization</li>
              <li>SMS and email OTP delivery</li>
              <li>Configurable external OTP providers including GTB, ZIB, Rolez, and generic third parties</li>
              <li>Multiple regional SMS providers plus delivery reports and callbacks</li>
              <li>Validation history, correlation IDs, Wibmo reporting, and legacy token compatibility</li>
            </ul>
          </div>

          <div>
            <h2>Architecture and technology</h2>
            <ul className="list">
              <li>Java 25 and Spring Boot 4 REST application</li>
              <li>Controllers for external APIs and services for token and authentication rules</li>
              <li>Provider abstractions for external OTP, SMS, and email systems</li>
              <li>JDBC DAOs backed by Microsoft SQL Server</li>
              <li>Redis for temporary OTP and request-session data</li>
              <li>Kafka for asynchronous validation reports</li>
              <li>Flyway and an internal migrator for database changes</li>
              <li>HSM integration for cryptographic authentication-token generation</li>
              <li>OpenAPI/Swagger, Actuator, structured logging, and Docker deployment</li>
            </ul>
          </div>

          <div>
            <h2>Why it matters</h2>
            <p>
              The platform sits in a security-sensitive part of the payments
              stack, so correctness, traceability, delivery reliability, and
              partner integration behavior all matter at the same time.
            </p>
          </div>
        </div>
      </Section>
    </div>
  )
}
